# Generated by Django 5.2.6 on 2025-09-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierapplication',
            name='other_commodities',
            field=models.TextField(blank=True, help_text='Other commodities not in the predefined list', null=True),
        ),
        migrations.AlterField(
            model_name='supplierapplication',
            name='commodities_to_supply',
            field=models.ManyToManyField(blank=True, help_text='Commodities the business intends to supply', related_name='applications', to='core.commodity'),
        ),
    ]
