# Generated by Django 5.2.6 on 2025-09-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_supplierapplication_other_commodities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierapplication',
            name='business_registration',
            field=models.FileField(blank=True, help_text='Business registration documents', null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='supplierapplication',
            name='fda_certificate',
            field=models.FileField(blank=True, help_text='FDA certificate for processed food', null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='supplierapplication',
            name='gcx_registration',
            field=models.FileField(blank=True, help_text='GCX registration documents', null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='supplierapplication',
            name='id_directors',
            field=models.FileField(blank=True, help_text='ID cards of directors', null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='supplierapplication',
            name='ppa_certificate',
            field=models.FileField(blank=True, help_text='PPA certificate', null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='supplierapplication',
            name='proof_of_office',
            field=models.FileField(blank=True, help_text='Proof of office documents', null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='supplierapplication',
            name='tax_clearance',
            field=models.FileField(blank=True, help_text='Tax clearance certificate', null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='supplierapplication',
            name='team_member_id',
            field=models.FileField(blank=True, help_text='Team member ID documents', null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='supplierapplication',
            name='vat_certificate',
            field=models.FileField(blank=True, help_text='VAT registration certificate', null=True, upload_to='applications/documents/'),
        ),
    ]
