# Generated by Django 5.2.6 on 2025-09-11 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_add_document_completion_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='mobile',
            field=models.CharField(help_text='Mobile number in Ghana format (0243123456, +233243123456, or 233243123456)', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in Ghana format: 0243123456, +233243123456, or 233243123456', regex='^(\\+?233|0?233|0)[1-9]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='supplierapplication',
            name='telephone',
            field=models.CharField(help_text='Business telephone number in Ghana format (0243123456, +233243123456, or 233243123456)', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in Ghana format: 0243123456, +233243123456, or 233243123456', regex='^(\\+?233|0?233|0)[1-9]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='supplierapplication',
            name='tracking_code',
            field=models.SlugField(help_text='Unique tracking code for the application', unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='telephone',
            field=models.CharField(blank=True, help_text='Telephone number in Ghana format (0243123456, +233243123456, or 233243123456)', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in Ghana format: 0243123456, +233243123456, or 233243123456', regex='^(\\+?233|0?233|0)[1-9]\\d{8}$')]),
        ),
    ]
