# Generated by Django 5.2.6 on 2025-09-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_nextofkin_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('NEEDS_MORE_DOCS', 'Needs More Documents'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', help_text='Current status of the application', max_length=20),
        ),
    ]
