# Generated by Django 5.2.6 on 2025-09-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_supplierapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierapplication',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', help_text='Current status of the application', max_length=20),
        ),
    ]
