# Generated by Django 5.2.6 on 2025-09-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_simplify_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierapplication',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF of application details', null=True, upload_to='applications/pdfs/'),
        ),
    ]
