# Generated by Django 5.2.6 on 2025-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_supplierapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierapplication',
            name='email',
            field=models.EmailField(help_text='Business email address', max_length=254),
        ),
    ]
