# Generated by Django 5.2.6 on 2025-09-24 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_remove_email_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReceiptVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srv_number', models.CharField(help_text='Unique SRV number', max_length=100, unique=True)),
                ('srv_date', models.DateField(help_text='SRV date')),
                ('description', models.TextField(help_text='SRV description')),
                ('delivery_location', models.CharField(help_text='Delivery location', max_length=200)),
                ('delivery_date', models.DateField(help_text='Expected delivery date')),
                ('actual_delivery_date', models.DateField(blank=True, help_text='Actual delivery date', null=True)),
                ('items_description', models.TextField(help_text='Description of items')),
                ('total_quantity', models.DecimalField(decimal_places=2, help_text='Total quantity', max_digits=10)),
                ('unit_of_measure', models.CharField(help_text='Unit of measure', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount', max_digits=15)),
                ('currency', models.CharField(default='GHS', help_text='Currency', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed')], default='PENDING', help_text='SRV status', max_length=20)),
                ('srv_document', models.FileField(blank=True, help_text='SRV document', null=True, upload_to='srvs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created the SRV', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_srvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Receipt Voucher',
                'verbose_name_plural': 'Store Receipt Vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=100, unique=True)),
                ('invoice_date', models.DateField(help_text='Invoice date')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal amount', max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate percentage', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax amount', max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount', max_digits=15)),
                ('currency', models.CharField(default='GHS', help_text='Currency', max_length=3)),
                ('payment_terms', models.CharField(choices=[('NET_15', 'Net 15'), ('NET_30', 'Net 30'), ('NET_45', 'Net 45'), ('NET_60', 'Net 60'), ('IMMEDIATE', 'Immediate')], default='NET_30', help_text='Payment terms', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid', max_digits=15)),
                ('paid_date', models.DateField(blank=True, help_text='Date payment was received', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Invoice status', max_length=20)),
                ('invoice_document', models.FileField(blank=True, help_text='Invoice document', null=True, upload_to='invoices/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created the invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('srv', models.ForeignKey(help_text='Associated SRV', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='applications.storereceiptvoucher')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='Unique contract number', max_length=100, unique=True)),
                ('contract_type', models.CharField(choices=[('SUPPLY_AGREEMENT', 'Supply Agreement'), ('FRAMEWORK_AGREEMENT', 'Framework Agreement'), ('SERVICE_AGREEMENT', 'Service Agreement'), ('OTHER', 'Other')], default='SUPPLY_AGREEMENT', help_text='Type of contract', max_length=50)),
                ('title', models.CharField(help_text='Contract title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Contract description')),
                ('contract_file', models.FileField(help_text='Uploaded contract document', upload_to='contracts/%Y/%m/')),
                ('start_date', models.DateField(help_text='Contract start date')),
                ('end_date', models.DateField(help_text='Contract end date')),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, help_text='Total contract value', max_digits=15, null=True)),
                ('currency', models.CharField(default='GHS', help_text='Contract currency', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='DRAFT', help_text='Contract status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='Associated supplier application', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='applications.supplierapplication')),
                ('created_by', models.ForeignKey(help_text='Admin who created the contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Contract',
                'verbose_name_plural': 'Supplier Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='contract',
            field=models.ForeignKey(help_text='Associated contract', on_delete=django.db.models.deletion.CASCADE, related_name='srvs', to='applications.suppliercontract'),
        ),
    ]
