# Generated by Django 5.2.6 on 2025-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_contractcommodity_deliverytracking_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person name', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
    ]
