# Generated by Django 5.2.6 on 2025-09-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_alter_school_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
    ]
