# Generated by Django 5.2.6 on 2025-09-24 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_allow_null_contact_fields'),
        ('core', '0005_commodity_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_document',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='srv',
        ),
        migrations.RemoveField(
            model_name='storereceiptvoucher',
            name='actual_delivery_date',
        ),
        migrations.RemoveField(
            model_name='storereceiptvoucher',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='storereceiptvoucher',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='storereceiptvoucher',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='storereceiptvoucher',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='storereceiptvoucher',
            name='description',
        ),
        migrations.RemoveField(
            model_name='storereceiptvoucher',
            name='items_description',
        ),
        migrations.RemoveField(
            model_name='storereceiptvoucher',
            name='srv_date',
        ),
        migrations.RemoveField(
            model_name='storereceiptvoucher',
            name='srv_document',
        ),
        migrations.RemoveField(
            model_name='storereceiptvoucher',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='delivery_commodity',
            field=models.ForeignKey(blank=True, help_text='Commodity that was delivered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.commodity'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='delivery_region',
            field=models.ForeignKey(blank=True, help_text='Region where delivery was made', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.region'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='delivery_school',
            field=models.ForeignKey(blank=True, help_text='School where delivery was made', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='applications.school'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_region',
            field=models.ForeignKey(help_text='Client region', on_delete=django.db.models.deletion.PROTECT, to='core.region', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_school',
            field=models.ForeignKey(help_text='Client school', on_delete=django.db.models.deletion.PROTECT, to='applications.school', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='commodity',
            field=models.ForeignKey(help_text='Commodity invoiced', on_delete=django.db.models.deletion.PROTECT, to='core.commodity', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document',
            field=models.FileField(blank=True, help_text='Invoice document', null=True, upload_to='invoices/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date of payment', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of commodity', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(help_text='Supplier who created the invoice', on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_of_measure',
            field=models.CharField(help_text='Unit of measure', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='commodity',
            field=models.ForeignKey(help_text='Commodity delivered', on_delete=django.db.models.deletion.PROTECT, to='core.commodity', null=True),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='delivery_region',
            field=models.ForeignKey(help_text='Region where goods were delivered', on_delete=django.db.models.deletion.PROTECT, to='core.region', null=True),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='delivery_school',
            field=models.ForeignKey(help_text='School where goods were delivered', on_delete=django.db.models.deletion.PROTECT, to='applications.school', null=True),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='document',
            field=models.FileField(blank=True, help_text='SRV document', null=True, upload_to='srvs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of commodity delivered', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='received_by',
            field=models.CharField(help_text='Name of person who received the goods', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='received_by_designation',
            field=models.CharField(help_text='Designation of person who received the goods', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='supplier',
            field=models.ForeignKey(help_text='Supplier who created the SRV', on_delete=django.db.models.deletion.CASCADE, related_name='created_srvs', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='contract_commodity',
            field=models.ForeignKey(blank=True, help_text='Associated contract commodity (if from contract)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='applications.contractcommodity'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Invoice status', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Subtotal amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='storereceiptvoucher',
            name='delivery_date',
            field=models.DateField(help_text='Date of delivery'),
        ),
        migrations.AlterField(
            model_name='storereceiptvoucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='SRV status', max_length=20),
        ),
        migrations.AlterField(
            model_name='storereceiptvoucher',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount for this SRV', max_digits=12),
        ),
        migrations.AlterField(
            model_name='storereceiptvoucher',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price of the commodity', max_digits=10),
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(help_text='Unique waybill number', max_length=100, unique=True)),
                ('transporter_name', models.CharField(help_text='Name of the transporter', max_length=200)),
                ('vehicle_number', models.CharField(help_text='Vehicle registration number', max_length=50)),
                ('driver_name', models.CharField(help_text='Name of the driver', max_length=200)),
                ('driver_license', models.CharField(blank=True, help_text="Driver's license number", max_length=50)),
                ('origin', models.CharField(help_text='Origin of the goods', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of commodity', max_digits=10)),
                ('unit_of_measure', models.CharField(help_text='Unit of measure', max_length=50)),
                ('loading_date', models.DateTimeField(help_text='Date and time of loading')),
                ('expected_delivery_date', models.DateTimeField(help_text='Expected delivery date and time')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Waybill status', max_length=20)),
                ('document', models.FileField(blank=True, help_text='Waybill document', null=True, upload_to='waybills/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(help_text='Commodity being transported', on_delete=django.db.models.deletion.PROTECT, to='core.commodity')),
                ('destination_region', models.ForeignKey(help_text='Destination region', on_delete=django.db.models.deletion.PROTECT, to='core.region')),
                ('destination_school', models.ForeignKey(help_text='Destination school', on_delete=django.db.models.deletion.PROTECT, to='applications.school')),
                ('supplier', models.ForeignKey(help_text='Supplier who created the waybill', on_delete=django.db.models.deletion.CASCADE, related_name='created_waybills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waybill',
                'verbose_name_plural': 'Waybills',
                'ordering': ['-created_at'],
            },
        ),
    ]
