# Generated by Django 5.2.6 on 2025-09-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_add_new_document_models'),
    ]

    operations = [
    ]
