# Generated by Django 5.2.6 on 2025-09-25 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_merge_20250925_0041'),
        ('core', '0001_initial'),
    ]

    operations = [
        # Add missing fields to StoreReceiptVoucher
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='supplier',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_srvs',
                to='auth.user',
                help_text='Supplier who created the SRV',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='delivery_region',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.region',
                help_text='Region where goods were delivered',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='delivery_school',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='applications.school',
                help_text='School where goods were delivered',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='commodity',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.commodity',
                help_text='Commodity delivered',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='quantity',
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                help_text='Quantity of commodity delivered',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='received_by',
            field=models.CharField(
                max_length=200,
                help_text='Name of person who received the goods',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='received_by_designation',
            field=models.CharField(
                max_length=100,
                help_text='Designation of person who received the goods',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='document',
            field=models.FileField(
                upload_to='srvs/%Y/%m/',
                null=True,
                blank=True,
                help_text='SRV document'
            ),
        ),
        migrations.AddField(
            model_name='storereceiptvoucher',
            name='notes',
            field=models.TextField(
                blank=True,
                help_text='Additional notes',
                null=True
            ),
        ),
        
        # Add missing fields to Invoice
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_invoices',
                to='auth.user',
                help_text='Supplier who created the invoice',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_region',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.region',
                help_text='Region of the client school',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_school',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='applications.school',
                help_text='Client school',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='commodity',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.commodity',
                help_text='Commodity invoiced',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                help_text='Quantity of commodity invoiced',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_of_measure',
            field=models.CharField(
                max_length=50,
                help_text='Unit of measure',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price',
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                help_text='Unit price of the commodity',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document',
            field=models.FileField(
                upload_to='invoices/%Y/%m/',
                null=True,
                blank=True,
                help_text='Invoice document'
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(
                max_length=100,
                help_text='Payment reference number',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(
                null=True,
                blank=True,
                help_text='Date payment was received'
            ),
        ),
        
        # Create Waybill table
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(max_length=100, unique=True, help_text='Unique waybill number')),
                ('transporter_name', models.CharField(max_length=200, help_text='Name of the transporter')),
                ('vehicle_number', models.CharField(max_length=50, help_text='Vehicle registration number')),
                ('driver_name', models.CharField(max_length=200, help_text='Driver name')),
                ('driver_license', models.CharField(max_length=50, help_text='Driver license number')),
                ('origin', models.CharField(max_length=200, help_text='Origin location')),
                ('loading_date', models.DateField(help_text='Date of loading')),
                ('expected_delivery_date', models.DateField(help_text='Expected delivery date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('document', models.FileField(blank=True, help_text='Waybill document', null=True, upload_to='waybills/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(help_text='Commodity being transported', on_delete=django.db.models.deletion.PROTECT, to='core.commodity')),
                ('destination_region', models.ForeignKey(help_text='Destination region', on_delete=django.db.models.deletion.PROTECT, to='core.region')),
                ('destination_school', models.ForeignKey(help_text='Destination school', on_delete=django.db.models.deletion.PROTECT, to='applications.school')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity being transported', max_digits=10)),
                ('supplier', models.ForeignKey(help_text='Supplier who created the waybill', on_delete=django.db.models.deletion.CASCADE, related_name='created_waybills', to='auth.user')),
                ('unit_of_measure', models.CharField(help_text='Unit of measure', max_length=50)),
            ],
            options={
                'verbose_name': 'Waybill',
                'verbose_name_plural': 'Waybills',
                'ordering': ['-created_at'],
            },
        ),
    ]
