# Generated by Django 5.2.6 on 2025-09-25 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_add_missing_document_columns'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(max_length=100, unique=True, help_text='Unique waybill number')),
                ('transporter_name', models.CharField(max_length=200, help_text='Name of the transporter')),
                ('vehicle_number', models.CharField(max_length=50, help_text='Vehicle registration number')),
                ('driver_name', models.CharField(max_length=200, help_text='Driver name')),
                ('driver_license', models.CharField(max_length=50, help_text='Driver license number')),
                ('origin', models.CharField(max_length=200, help_text='Origin location')),
                ('loading_date', models.DateField(help_text='Date of loading')),
                ('expected_delivery_date', models.DateField(help_text='Expected delivery date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('document', models.FileField(blank=True, help_text='Waybill document', null=True, upload_to='waybills/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(help_text='Commodity being transported', on_delete=django.db.models.deletion.PROTECT, to='core.commodity')),
                ('destination_region', models.ForeignKey(help_text='Destination region', on_delete=django.db.models.deletion.PROTECT, to='core.region')),
                ('destination_school', models.ForeignKey(help_text='Destination school', on_delete=django.db.models.deletion.PROTECT, to='applications.school')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity being transported', max_digits=10)),
                ('supplier', models.ForeignKey(help_text='Supplier who created the waybill', on_delete=django.db.models.deletion.CASCADE, related_name='created_waybills', to='auth.user')),
                ('unit_of_measure', models.CharField(help_text='Unit of measure', max_length=50)),
            ],
            options={
                'verbose_name': 'Waybill',
                'verbose_name_plural': 'Waybills',
                'ordering': ['-created_at'],
            },
        ),
    ]
