# Generated by Django 5.2.6 on 2025-09-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_create_waybill_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytracking',
            name='invoice_number',
            field=models.CharField(
                max_length=100,
                help_text='Invoice number',
                null=True,
                blank=True
            ),
        ),
    ]
