# Generated by Django 5.2.6 on 2025-09-25 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_add_invoice_number_to_delivery'),
        ('core', '0006_add_unit_of_measure_to_commodity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytracking',
            name='delivery_commodity',
            field=models.ForeignKey(blank=True, help_text='Legacy single commodity field (deprecated - use commodities relationship)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_deliveries', to='core.commodity'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_region',
            field=models.ForeignKey(blank=True, help_text='Client region', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.region'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date of payment', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity of commodity', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier who created the invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storereceiptvoucher',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier who created the SRV', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_srvs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='driver_license',
            field=models.CharField(blank=True, help_text="Driver's license number", max_length=50),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='driver_name',
            field=models.CharField(help_text='Name of the driver', max_length=200),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='expected_delivery_date',
            field=models.DateTimeField(help_text='Expected delivery date and time'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='loading_date',
            field=models.DateTimeField(help_text='Date and time of loading'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes', null=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='origin',
            field=models.CharField(help_text='Origin of the goods', max_length=200),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of commodity', max_digits=10),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Waybill status', max_length=20),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='supplier',
            field=models.ForeignKey(help_text='Supplier who created the waybill', on_delete=django.db.models.deletion.CASCADE, related_name='created_waybills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DeliveryCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of commodity delivered', max_digits=10)),
                ('unit_of_measure', models.CharField(help_text='Unit of measure for the quantity', max_length=50)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Unit price of the commodity', max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for this commodity', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(help_text='Commodity delivered', on_delete=django.db.models.deletion.PROTECT, to='core.commodity')),
                ('delivery', models.ForeignKey(help_text='Associated delivery', on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='applications.deliverytracking')),
            ],
            options={
                'verbose_name': 'Delivery Commodity',
                'verbose_name_plural': 'Delivery Commodities',
                'unique_together': {('delivery', 'commodity')},
            },
        ),
    ]
