# Generated by Django 5.2.6 on 2025-09-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_add_delivery_commodity_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytracking',
            name='quantity_delivered',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual quantity delivered (legacy field)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text='Unit of measure (legacy field)', max_length=50, null=True),
        ),
    ]
