# Generated by Django 5.2.6 on 2025-09-26 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_make_delivery_quantity_fields_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Document description', null=True)),
                ('document_type', models.CharField(choices=[('CONTRACT_TEMPLATE', 'Contract Template'), ('TERMS_CONDITIONS', 'Terms & Conditions'), ('PRICING_SCHEDULE', 'Pricing Schedule'), ('DELIVERY_SCHEDULE', 'Delivery Schedule'), ('PAYMENT_TERMS', 'Payment Terms'), ('SPECIFICATIONS', 'Technical Specifications'), ('LEGAL_DOCUMENTS', 'Legal Documents'), ('OTHER', 'Other')], help_text='Type of contract document', max_length=50)),
                ('document_file', models.FileField(help_text='Contract document file', upload_to='contract_documents/%Y/%m/')),
                ('version', models.CharField(default='1.0', help_text='Document version', max_length=20)),
                ('is_current_version', models.BooleanField(default=True, help_text='Is this the current version of the document?')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Document status', max_length=20)),
                ('effective_from', models.DateField(help_text='Date from which this document is effective')),
                ('effective_until', models.DateField(blank=True, help_text='Date until which this document is effective (optional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this document', on_delete=django.db.models.deletion.CASCADE, related_name='created_contract_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Document',
                'verbose_name_plural': 'Contract Documents',
                'ordering': ['-created_at'],
                'unique_together': {('title', 'version')},
            },
        ),
    ]
