# Generated by Django 5.2.6 on 2025-09-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_contractdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(choices=[('CONTRACT_TEMPLATE', 'Contract Template'), ('TERMS_CONDITIONS', 'Terms & Conditions'), ('PRICING_SCHEDULE', 'Pricing Schedule'), ('DELIVERY_SCHEDULE', 'Delivery Schedule'), ('PAYMENT_TERMS', 'Payment Terms'), ('SPECIFICATIONS', 'Technical Specifications'), ('LEGAL_DOCUMENTS', 'Legal Documents'), ('SUPPLIER_GUIDE', 'Supplier Guide'), ('QUALITY_STANDARDS', 'Quality Standards'), ('OTHER', 'Other')], help_text='Unique code for the contract document requirement', unique=True)),
                ('label', models.CharField(help_text='Display label for the requirement', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what documents are required')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this document is mandatory for contracts')),
                ('condition_note', models.TextField(blank=True, help_text="Additional conditions or notes (e.g., 'Required for supply agreements only')")),
                ('allowed_extensions', models.JSONField(default=list, help_text='List of allowed file extensions')),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, help_text='Maximum file size in MB')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this requirement is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Document Requirement',
                'verbose_name_plural': 'Contract Document Requirements',
                'db_table': 'applications_contract_document_requirement',
                'ordering': ['label'],
            },
        ),
        migrations.RemoveField(
            model_name='contractdocument',
            name='document_type',
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='requirement',
            field=models.ForeignKey(blank=True, help_text='Document requirement this document fulfills', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.contractdocumentrequirement'),
        ),
    ]
