# Generated by Django 5.2.6 on 2025-09-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_contractdocumentrequirement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdocument',
            name='category',
            field=models.CharField(choices=[('STATIC', 'Static Document'), ('DYNAMIC', 'Dynamic Document'), ('CONTRACT_SPECIFIC', 'Contract Specific')], default='STATIC', help_text='Category of the document', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractDocumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this document is required for this contract')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_contract_documents', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_assignments', to='applications.suppliercontract')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_assignments', to='applications.contractdocument')),
            ],
            options={
                'verbose_name': 'Contract Document Assignment',
                'verbose_name_plural': 'Contract Document Assignments',
                'unique_together': {('contract', 'document')},
            },
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='assigned_contracts',
            field=models.ManyToManyField(blank=True, help_text='Contracts this document is assigned to', related_name='assigned_documents', through='applications.ContractDocumentAssignment', to='applications.suppliercontract'),
        ),
        migrations.CreateModel(
            name='ContractSigning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('SIGNED', 'Signed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('signature_file', models.FileField(blank=True, help_text='Digital signature file', null=True, upload_to='contract_signatures/%Y/%m/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signings', to='applications.suppliercontract')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Signing',
                'verbose_name_plural': 'Contract Signings',
                'ordering': ['-created_at'],
                'unique_together': {('contract', 'supplier')},
            },
        ),
    ]
