# Generated by Django 5.2.6 on 2025-09-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_contractdocument_category_contractdocumentassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdocumentrequirement',
            name='code',
            field=models.SlugField(help_text="Unique code for the contract document requirement (e.g., 'CONTRACT_TEMPLATE', 'CUSTOM_DOC_1')", unique=True),
        ),
    ]
