# Generated by Django 5.2.6 on 2025-09-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_alter_contractdocumentrequirement_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdocument',
            name='document_file',
            field=models.FileField(blank=True, help_text='Contract document file (required for static documents)', null=True, upload_to='contract_documents/%Y/%m/'),
        ),
    ]
