# Generated by Django 5.2.6 on 2025-09-27 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_alter_contractdocument_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytracking',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Associated contract (if delivery is for a contract)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='applications.suppliercontract'),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='contract_commodity',
            field=models.ForeignKey(blank=True, help_text='Associated contract commodity (if from contract) - DEPRECATED', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='applications.contractcommodity'),
        ),
    ]
