# Generated by Django 5.2.6 on 2025-09-27 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_deliverytracking_contract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytracking',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='Date when delivery was rejected', null=True),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Admin who rejected the delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
    ]
