# Generated by Django 5.2.6 on 2025-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_deliverytracking_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycommodity',
            name='unit_of_measure',
            field=models.CharField(help_text="Unit of measure for the quantity (e.g., '100kg bag', '1 crate', '50kg sack')", max_length=50),
        ),
    ]
