# Generated by Django 4.2.24 on 2025-10-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0032_alter_deliverycommodity_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierapplication',
            name='registration_number',
            field=models.CharField(blank=True, default='', help_text='Business registration number', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierapplication',
            name='tin_number',
            field=models.CharField(blank=True, default='', help_text='Tax Identification Number (TIN)', max_length=20),
        ),
    ]
