# Generated by Django 5.2.6 on 2025-09-09 18:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the commodity', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the commodity')),
                ('is_processed_food', models.BooleanField(default=False, help_text='Whether this commodity requires FDA certification')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this commodity is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Commodities',
                'db_table': 'core_commodity',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short code for the region (e.g., 'AR', 'AS')", max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('name', models.CharField(help_text='Full name of the region', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this region is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'core_region',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Action performed (e.g., 'APPROVE_APPLICATION', 'REJECT_APPLICATION')", max_length=100)),
                ('model_name', models.CharField(help_text='Model that was affected', max_length=100)),
                ('object_id', models.CharField(help_text='ID of the affected object', max_length=100)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'core_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the warehouse', max_length=200)),
                ('city', models.CharField(help_text='City where the warehouse is located', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Full address of the warehouse')),
                ('contact_person', models.CharField(blank=True, help_text='Contact person at the warehouse', max_length=100)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this warehouse is currently operational')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(help_text='Region where the warehouse is located', on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.region')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'core_warehouse',
                'ordering': ['name'],
            },
        ),
    ]
