# Generated by Django 5.2.6 on 2025-09-15 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Commodities'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='is_processed_food',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(default='System action', help_text='Description of the action'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('APPLICATION_CREATED', 'Application Created'), ('APPLICATION_UPDATED', 'Application Updated'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('STATUS_CHANGED', 'Status Changed'), ('REQUEST_DOCUMENTS', 'Request Documents'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('SETTINGS_CHANGED', 'Settings Changed')], help_text='Type of action performed', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional details about the action'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='commodity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='region',
            table=None,
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GCX Admin Portal', help_text='Name of the admin portal', max_length=200)),
                ('site_description', models.TextField(blank=True, help_text='Description of the admin portal')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode to restrict access')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to display during maintenance mode')),
                ('email_from_name', models.CharField(default='GCX eServices', help_text='Default sender name for emails', max_length=100)),
                ('email_from_address', models.EmailField(default='noreply@gcx.com.gh', help_text='Default sender email address', max_length=254)),
                ('email_reply_to', models.EmailField(blank=True, help_text='Reply-to email address', max_length=254)),
                ('sms_from_name', models.CharField(default='GCX', help_text='Default sender name for SMS', max_length=100)),
                ('notification_api_url', models.URLField(default='https://api.gcx.com.gh/notification-api/public', help_text='External notification API URL')),
                ('notification_timeout', models.PositiveIntegerField(default=30, help_text='Notification API timeout in seconds')),
                ('application_auto_approve', models.BooleanField(default=False, help_text='Automatically approve applications when all documents are verified')),
                ('application_approval_days', models.PositiveIntegerField(default=7, help_text='Days to wait before auto-approval')),
                ('document_verification_required', models.BooleanField(default=True, help_text='Require manual verification of uploaded documents')),
                ('password_min_length', models.PositiveIntegerField(default=8, help_text='Minimum password length')),
                ('password_require_special', models.BooleanField(default=True, help_text='Require special characters in passwords')),
                ('session_timeout', models.PositiveIntegerField(default=480, help_text='Session timeout in minutes')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, help_text='Maximum login attempts before lockout')),
                ('max_file_size', models.PositiveIntegerField(default=10, help_text='Maximum file size in MB')),
                ('allowed_file_types', models.TextField(default='pdf,doc,docx,jpg,jpeg,png', help_text='Comma-separated list of allowed file extensions')),
                ('audit_log_retention_days', models.PositiveIntegerField(default=365, help_text='Number of days to retain audit logs')),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', help_text='System log level', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'core_system_settings',
            },
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
