# Generated by Django 5.2.6 on 2025-09-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_commodity_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='admin_notification_email',
            field=models.EmailField(default='admin@gcx.com.gh', help_text='Email address to receive notifications for new applications', max_length=254),
        ),
    ]
