# Generated by Django 5.2.6 on 2025-09-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings_admin_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='image',
            field=models.ImageField(blank=True, help_text='Image representing this commodity', null=True, upload_to='commodities/'),
        ),
    ]
