# Generated by Django 5.2.6 on 2025-09-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_commodity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='unit_of_measure',
            field=models.CharField(default='kg', help_text='Default unit of measure for this commodity (e.g., kg, bags, pieces)', max_length=50),
        ),
    ]
