# Generated by Django 4.2.24 on 2025-10-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sms_api_key',
            field=models.CharField(blank=True, help_text='SMS API key or username', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_api_secret',
            field=models.CharField(blank=True, help_text='SMS API secret or password', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('africas_talking', "Africa's Talking"), ('custom', 'Custom API')], default='twilio', help_text='SMS service provider', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_sender_id',
            field=models.CharField(blank=True, help_text='SMS sender ID or phone number', max_length=20),
        ),
    ]
