# Generated by Django 4.2.24 on 2025-10-23 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_systemsettings_sms_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='log_level',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='process_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='response_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='response_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='server_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='audit_log_enabled',
            field=models.BooleanField(default=True, help_text='Enable audit logging for system activities'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Create Record'), ('UPDATE', 'Update Record'), ('DELETE', 'Delete Record'), ('VIEW', 'View Record'), ('DOWNLOAD', 'Download File'), ('UPLOAD', 'Upload File'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SEND_EMAIL', 'Send Email'), ('SEND_SMS', 'Send SMS'), ('EXPORT', 'Export Data'), ('IMPORT', 'Import Data'), ('SETTINGS_CHANGE', 'Settings Change'), ('PASSWORD_CHANGE', 'Password Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('SYSTEM_ERROR', 'System Error'), ('SECURITY_EVENT', 'Security Event')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='commodities/'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='is_processed_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='unit_of_measure',
            field=models.CharField(default='kg', max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='allowed_file_types',
            field=models.TextField(default='pdf,doc,docx,jpg,jpeg,png', help_text='Comma-separated list of allowed file types'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='application_approval_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days to wait before auto-approving applications'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='application_auto_approve',
            field=models.BooleanField(default=False, help_text='Automatically approve applications without manual review'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='document_verification_required',
            field=models.BooleanField(default=True, help_text='Require document verification before application approval'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='max_login_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Maximum login attempts before account lockout'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp', 'action'], name='core_auditl_timesta_368b53_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='core_auditl_severit_4032b9_idx'),
        ),
        migrations.AlterModelTable(
            name='systemsettings',
            table=None,
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
