# Generated by Django 5.2.6 on 2025-09-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Review comment')),
                ('is_internal', models.BooleanField(default=True, help_text='Whether this is an internal comment (not visible to applicant)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='Application being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='applications.supplierapplication')),
                ('reviewer', models.ForeignKey(help_text='User who made the comment', on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Comment',
                'verbose_name_plural': 'Review Comments',
                'db_table': 'reviews_review_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_MORE_DOCS', 'Request More Documents'), ('PENDING', 'Pending Review')], help_text='Review decision', max_length=20)),
                ('reason', models.TextField(help_text='Reason for the decision')),
                ('is_final', models.BooleanField(default=False, help_text='Whether this is the final decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='Application being decided on', on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='applications.supplierapplication')),
                ('reviewer', models.ForeignKey(help_text='User making the decision', on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Decision',
                'verbose_name_plural': 'Review Decisions',
                'db_table': 'reviews_review_decision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_registration', models.BooleanField(default=False)),
                ('vat_certificate', models.BooleanField(default=False)),
                ('ppa_certificate', models.BooleanField(default=False)),
                ('tax_clearance', models.BooleanField(default=False)),
                ('proof_of_office', models.BooleanField(default=False)),
                ('id_directors', models.BooleanField(default=False)),
                ('gcx_registration', models.BooleanField(default=False)),
                ('team_member_id', models.BooleanField(default=False)),
                ('fda_certificate', models.BooleanField(default=False)),
                ('bank_account', models.BooleanField(default=False)),
                ('contact_info', models.BooleanField(default=False)),
                ('business_details', models.BooleanField(default=False)),
                ('team_members', models.BooleanField(default=False)),
                ('next_of_kin', models.BooleanField(default=False)),
                ('declaration', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False, help_text='Whether all required items are complete')),
                ('overall_notes', models.TextField(blank=True, help_text='Overall review notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='Application being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='review_checklist', to='applications.supplierapplication')),
                ('reviewer', models.ForeignKey(help_text='User conducting the review', on_delete=django.db.models.deletion.CASCADE, related_name='review_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Checklist',
                'verbose_name_plural': 'Review Checklists',
                'db_table': 'reviews_review_checklist',
                'unique_together': {('application', 'reviewer')},
            },
        ),
    ]
