# Generated by Django 5.2.6 on 2025-09-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationanalytics_notificationlog_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAUSED', 'Paused'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered'), ('BOUNCED', 'Bounced'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked')], default='PENDING', help_text='Status of the notification', max_length=20),
        ),
    ]
