# Generated by Django 5.2.6 on 2025-09-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('APPLICATION_SUBMITTED', 'Application Submitted'), ('DOCUMENTS_REQUESTED', 'Documents Requested'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_CREATED', 'Account Created'), ('ADMIN_NOTIFICATION', 'Admin Notification')], help_text='Type of notification', max_length=50, unique=True),
        ),
    ]
