# Generated by Django 5.2.6 on 2025-09-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationtemplate_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('APPLICATION_SUBMITTED', 'Application Submitted'), ('DOCUMENTS_REQUESTED', 'Documents Requested'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_CREATED', 'Account Created'), ('ADMIN_NOTIFICATION', 'Admin Notification'), ('CONTRACT_AWARDED', 'Contract Awarded'), ('DELIVERY_SUBMITTED', 'Delivery Submitted'), ('DELIVERY_VERIFIED', 'Delivery Verified'), ('DELIVERY_REJECTED', 'Delivery Rejected')], help_text='Type of notification', max_length=50, unique=True),
        ),
    ]
